In [ ]:
pip install --upgrade 'google-cloud-bigquery[bqstorage, pandas]'

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: google-cloud-bigquery[bqstorage,pandas] in /usr/local/lib/python3.7/dist-packages (1.21.0)
Requirement already satisfied: google-cloud-core<2.0dev,>=1.0.3 in /usr/local/lib/python3.7/dist-packages (from google-cloud-bigquery[bqstorage,pandas]) (1.0.3)
Requirement already satisfied: protobuf>=3.6.0 in /usr/local/lib/python3.7/dist-packages (from google-cloud-bigquery[bqstorage,pandas]) (3.17.3)
Requirement already satisfied: google-resumable-media!=0.4.0,<0.5.0dev,>=0.3.1 in /usr/local/lib/python3.7/dist-packages (from google-cloud-bigquery[bqstorage,pandas]) (0.4.1)
Requirement already satisfied: pandas>=0.17.1 in /usr/local/lib/python3.7/dist-packages (from google-cloud-bigquery[bqstorage,pandas]) (1.3.5)
Requirement already satisfied: pyarrow!=0.14.0,>=0.13.0 in /usr/local/lib/python3.7/dist-packages (from google-cloud-bigquery[bqstorage,pandas]) (6.0.1)
Requirement already satisfied: google-cloud-bigquery-storage<2.0.0dev,>=0.6.0 in /usr/local/lib/python3.7/dist-packages (from google-cloud-bigquery[bqstorage,pandas]) (1.1.2)
Requirement already satisfied: google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5 in /usr/local/lib/python3.7/dist-packages (from google-cloud-bigquery-storage<2.0.0dev,>=0.6.0->google-cloud-bigquery[bqstorage,pandas]) (1.31.6)
Requirement already satisfied: setuptools>=40.3.0 in /usr/local/lib/python3.7/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-bigquery-storage<2.0.0dev,>=0.6.0->google-cloud-bigquery[bqstorage,pandas]) (57.4.0)
Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in /usr/local/lib/python3.7/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-bigquery-storage<2.0.0dev,>=0.6.0->google-cloud-bigquery[bqstorage,pandas]) (2.23.0)
Requirement already satisfied: six>=1.13.0 in /usr/local/lib/python3.7/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-bigquery-storage<2.0.0dev,>=0.6.0->google-cloud-bigquery[bqstorage,pandas]) (1.15.0)
Requirement already satisfied: pytz in /usr/local/lib/python3.7/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-bigquery-storage<2.0.0dev,>=0.6.0->google-cloud-bigquery[bqstorage,pandas]) (2022.2.1)
Requirement already satisfied: google-auth<2.0dev,>=1.25.0 in /usr/local/lib/python3.7/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-bigquery-storage<2.0.0dev,>=0.6.0->google-cloud-bigquery[bqstorage,pandas]) (1.35.0)
Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.6.0 in /usr/local/lib/python3.7/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-bigquery-storage<2.0.0dev,>=0.6.0->google-cloud-bigquery[bqstorage,pandas]) (1.56.4)
Requirement already satisfied: packaging>=14.3 in /usr/local/lib/python3.7/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-bigquery-storage<2.0.0dev,>=0.6.0->google-cloud-bigquery[bqstorage,pandas]) (21.3)
Requirement already satisfied: grpcio<2.0dev,>=1.29.0 in /usr/local/lib/python3.7/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-bigquery-storage<2.0.0dev,>=0.6.0->google-cloud-bigquery[bqstorage,pandas]) (1.47.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.7/dist-packages (from google-auth<2.0dev,>=1.25.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-bigquery-storage<2.0.0dev,>=0.6.0->google-cloud-bigquery[bqstorage,pandas]) (4.9)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.7/dist-packages (from google-auth<2.0dev,>=1.25.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-bigquery-storage<2.0.0dev,>=0.6.0->google-cloud-bigquery[bqstorage,pandas]) (0.2.8)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from google-auth<2.0dev,>=1.25.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-bigquery-storage<2.0.0dev,>=0.6.0->google-cloud-bigquery[bqstorage,pandas]) (4.2.4)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging>=14.3->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-bigquery-storage<2.0.0dev,>=0.6.0->google-cloud-bigquery[bqstorage,pandas]) (3.0.9)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.17.1->google-cloud-bigquery[bqstorage,pandas]) (1.21.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.17.1->google-cloud-bigquery[bqstorage,pandas]) (2.8.2)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /usr/local/lib/python3.7/dist-packages (from pyasn1-modules>=0.2.1->google-auth<2.0dev,>=1.25.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-bigquery-storage<2.0.0dev,>=0.6.0->google-cloud-bigquery[bqstorage,pandas]) (0.4.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-bigquery-storage<2.0.0dev,>=0.6.0->google-cloud-bigquery[bqstorage,pandas]) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-bigquery-storage<2.0.0dev,>=0.6.0->google-cloud-bigquery[bqstorage,pandas]) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-bigquery-storage<2.0.0dev,>=0.6.0->google-cloud-bigquery[bqstorage,pandas]) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-bigquery-storage<2.0.0dev,>=0.6.0->google-cloud-bigquery[bqstorage,pandas]) (2022.6.15)

In [ ]:
import os 
from google.cloud import bigquery

creds = 'gbqpy.json'
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = creds

client = bigquery.Client()
q = (f'SELECT * From `live-training-project-359704.analytics_327675126.events_20220816` ')
query = client.query(q)
df = query.result().to_dataframe()

df

,event_date,event_timestamp,event_name,event_params,event_previous_timestamp,event_value_in_usd,event_bundle_sequence_id,event_server_timestamp_offset,user_id,user_pseudo_id,...,user_ltv,device,geo,app_info,traffic_source,stream_id,platform,event_dimensions,ecommerce,items
0,20220816,1660699285481236,first_visit,"[{'key': 'ga_session_number', 'value': {'strin...",None,None,-1359124716,None,None,1204708313.1660699285,...,"{'revenue': 0.0, 'currency': 'USD'}","{'category': 'desktop', 'mobile_brand_name': '...","{'continent': 'Africa', 'country': 'Egypt', 'r...",None,"{'name': '(referral)', 'medium': 'referral', '...",3988275774,WEB,None,None,[]
1,20220816,1660699285481236,session_start,"[{'key': 'ga_session_number', 'value': {'strin...",None,None,-1359124716,None,None,1204708313.1660699285,...,"{'revenue': 0.0, 'currency': 'USD'}","{'category': 'desktop', 'mobile_brand_name': '...","{'continent': 'Africa', 'country': 'Egypt', 'r...",None,"{'name': '(referral)', 'medium': 'referral', '...",3988275774,WEB,None,None,[]
2,20220816,1660699285481236,page_view,"[{'key': 'page_location', 'value': {'string_va...",None,None,-1359124716,None,None,1204708313.1660699285,...,"{'revenue': 0.0, 'currency': 'USD'}","{'category': 'desktop', 'mobile_brand_name': '...","{'continent': 'Africa', 'country': 'Egypt', 'r...",None,"{'name': '(referral)', 'medium': 'referral', '...",3988275774,WEB,None,None,[]
3,20220816,1660699287970198,scroll,"[{'key': 'engaged_session_event', 'value': {'s...",None,None,-1356635754,None,None,1204708313.1660699285,...,"{'revenue': 0.0, 'currency': 'USD'}","{'category': 'desktop', 'mobile_brand_name': '...","{'continent': 'Africa', 'country': 'Egypt', 'r...",None,"{'name': '(referral)', 'medium': 'referral', '...",3988275774,WEB,None,None,[]
4,20220816,1660699287970198,user_engagement,"[{'key': 'page_referrer', 'value': {'string_va...",None,None,-1356635754,None,None,1204708313.1660699285,...,"{'revenue': 0.0, 'currency': 'USD'}","{'category': 'desktop', 'mobile_brand_name': '...","{'continent': 'Africa', 'country': 'Egypt', 'r...",None,"{'name': '(referral)', 'medium': 'referral', '...",3988275774,WEB,None,None,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,20220816,1660710858112414,page_view,"[{'key': 'page_location', 'value': {'string_va...",None,None,1623571870,None,None,130933001.1660710857,...,"{'revenue': 0.0, 'currency': 'USD'}","{'category': 'desktop', 'mobile_brand_name': '...","{'continent': 'Africa', 'country': 'Egypt', 'r...",None,"{'name': '(direct)', 'medium': '(none)', 'sour...",3988275774,WEB,None,None,[]
69,20220816,1660710860326891,scroll,"[{'key': 'session_engaged', 'value': {'string_...",None,None,1625786347,None,None,130933001.1660710857,...,"{'revenue': 0.0, 'currency': 'USD'}","{'category': 'desktop', 'mobile_brand_name': '...","{'continent': 'Africa', 'country': 'Egypt', 'r...",None,"{'name': '(direct)', 'medium': '(none)', 'sour...",3988275774,WEB,None,None,[]
70,20220816,1660710860326891,user_engagement,"[{'key': 'page_title', 'value': {'string_value...",None,None,1625786347,None,None,130933001.1660710857,...,"{'revenue': 0.0, 'currency': 'USD'}","{'category': 'desktop', 'mobile_brand_name': '...","{'continent': 'Africa', 'country': 'Egypt', 'r...",None,"{'name': '(direct)', 'medium': '(none)', 'sour...",3988275774,WEB,None,None,[]
71,20220816,1660710866196773,page_view,"[{'key': 'page_title', 'value': {'string_value...",None,None,1631656229,None,None,130933001.1660710857,...,"{'revenue': 0.0, 'currency': 'USD'}","{'category': 'desktop', 'mobile_brand_name': '...","{'continent': 'Africa', 'country': 'Egypt', 'r...",None,"{'name': '(direct)', 'medium': '(none)', 'sour...",3988275774,WEB,None,None,[]
72,20220816,1660710866196773,scroll,"[{'key': 'session_engaged', 'value': {'string_...",None,None,1631656229,None,None,130933001.1660710857,...,"{'revenue': 0.0, 'currency': 'USD'}","{'category': 'desktop', 'mobile_brand_name': '...","{'continent': 'Africa', 'country': 'Egypt', 'r...",None,"{'name': '(direct)', 'medium': '(none)', 'sour...",3988275774,WEB,None,None,[]

In [ ]:
df_geo = df[['geo']]
df_geo = pd.json_normalize(df_geo['geo'])
df_geo

   continent country             region   city    sub_continent      metro
0     Africa   Egypt  Cairo Governorate  Cairo  Northern Africa  (not set)
1     Africa   Egypt  Cairo Governorate  Cairo  Northern Africa  (not set)
2     Africa   Egypt  Cairo Governorate  Cairo  Northern Africa  (not set)
3     Africa   Egypt  Cairo Governorate  Cairo  Northern Africa  (not set)
4     Africa   Egypt  Cairo Governorate  Cairo  Northern Africa  (not set)
..       ...     ...                ...    ...              ...        ...
68    Africa   Egypt  Cairo Governorate  Cairo  Northern Africa  (not set)
69    Africa   Egypt  Cairo Governorate  Cairo  Northern Africa  (not set)
70    Africa   Egypt  Cairo Governorate  Cairo  Northern Africa  (not set)
71    Africa   Egypt  Cairo Governorate  Cairo  Northern Africa  (not set)
72    Africa   Egypt  Cairo Governorate  Cairo  Northern Africa  (not set)

[73 rows x 6 columns]

In [ ]:
df_device = df[['device']]
df_device = pd.json_normalize(df_device['device'])
df_device

,category,mobile_brand_name,mobile_model_name,mobile_marketing_name,mobile_os_hardware_model,operating_system,operating_system_version,vendor_id,advertising_id,language,is_limited_ad_tracking,time_zone_offset_seconds,browser,browser_version,web_info.browser,web_info.browser_version,web_info.hostname
0,desktop,Google,Chrome,None,None,Windows,Windows 10,None,None,en-us,No,None,None,None,Chrome,104.0.0.0,ahmed-mohamed3.github.io
1,desktop,Google,Chrome,None,None,Windows,Windows 10,None,None,en-us,No,None,None,None,Chrome,104.0.0.0,ahmed-mohamed3.github.io
2,desktop,Google,Chrome,None,None,Windows,Windows 10,None,None,en-us,No,None,None,None,Chrome,104.0.0.0,ahmed-mohamed3.github.io
3,desktop,Google,Chrome,None,None,Windows,Windows 10,None,None,en-us,No,None,None,None,Chrome,104.0.0.0,ahmed-mohamed3.github.io
4,desktop,Google,Chrome,None,None,Windows,Windows 10,None,None,en-us,No,None,None,None,Chrome,104.0.0.0,ahmed-mohamed3.github.io
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,desktop,Google,Chrome,None,None,Windows,Windows 10,None,None,en-us,No,None,None,None,Chrome,104.0.0.0,ahmed-mohamed3.github.io
69,desktop,Google,Chrome,None,None,Windows,Windows 10,None,None,en-us,No,None,None,None,Chrome,104.0.0.0,ahmed-mohamed3.github.io
70,desktop,Google,Chrome,None,None,Windows,Windows 10,None,None,en-us,No,None,None,None,Chrome,104.0.0.0,ahmed-mohamed3.github.io
71,desktop,Google,Chrome,None,None,Windows,Windows 10,None,None,en-us,No,None,None,None,Chrome,104.0.0.0,ahmed-mohamed3.github.io
72,desktop,Google,Chrome,None,None,Windows,Windows 10,None,None,en-us,No,None,None,None,Chrome,104.0.0.0,ahmed-mohamed3.github.io

In [ ]:
df_traffic = df[['traffic_source']]
df_traffic = pd.json_normalize(df_traffic['traffic_source'])
df_traffic

          name    medium      source
0   (referral)  referral  github.com
1   (referral)  referral  github.com
2   (referral)  referral  github.com
3   (referral)  referral  github.com
4   (referral)  referral  github.com
..         ...       ...         ...
68    (direct)    (none)    (direct)
69    (direct)    (none)    (direct)
70    (direct)    (none)    (direct)
71    (direct)    (none)    (direct)
72    (direct)    (none)    (direct)

[73 rows x 3 columns]

In [ ]:
df_params = df[['event_params']]
df_params = df_params.explode('event_params')
df_params = pd.json_normalize(df_params['event_params'])
df_params

,key,value.string_value,value.int_value,value.float_value,value.double_value
0,ga_session_number,None,1.000000e+00,None,None
1,page_title,Welcome,NaN,None,None
2,engaged_session_event,None,1.000000e+00,None,None
3,page_location,https://ahmed-mohamed3.github.io/googleanalytics/,NaN,None,None
4,page_referrer,https://github.com/Ahmed-mohamed3/googleanalyt...,NaN,None,None
...,...,...,...,...,...
715,ga_session_id,None,1.660711e+09,None,None
716,ga_session_number,None,1.000000e+00,None,None
717,engaged_session_event,None,1.000000e+00,None,None
718,page_title,Welcome,NaN,None,None
719,percent_scrolled,None,9.000000e+01,None,None

In [ ]:
df_user_ltv = df[['user_ltv' ]]
df_user_ltv = pd.json_normalize(df_user_ltv['user_ltv'])
df_user_ltv

    revenue currency
0       0.0      USD
1       0.0      USD
2       0.0      USD
3       0.0      USD
4       0.0      USD
..      ...      ...
68      0.0      USD
69      0.0      USD
70      0.0      USD
71      0.0      USD
72      0.0      USD

[73 rows x 2 columns]

In [ ]:
df_privacy_info = df[['privacy_info' ]]
df_privacy_info = pd.json_normalize(df_privacy_info['privacy_info'])
df_privacy_info

   analytics_storage ads_storage uses_transient_token
0               None        None                   No
1               None        None                   No
2               None        None                   No
3               None        None                   No
4               None        None                   No
..               ...         ...                  ...
68              None        None                   No
69              None        None                   No
70              None        None                   No
71              None        None                   No
72              None        None                   No

[73 rows x 3 columns]